//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Map4D.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Map4D.Resources.HomeText", typeof(HomeText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng giá.
        /// </summary>
        public static string Bảnggiá {
            get {
                return ResourceManager.GetString("Bảnggiá", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        public static string Côngty {
            get {
                return ResourceManager.GetString("Côngty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giải pháp.
        /// </summary>
        public static string Giảipháp {
            get {
                return ResourceManager.GetString("Giảipháp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản Phẩm.
        /// </summary>
        public static string SảnPhẩm {
            get {
                return ResourceManager.GetString("SảnPhẩm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu.
        /// </summary>
        public static string TàiLiệu {
            get {
                return ResourceManager.GetString("TàiLiệu", resourceCulture);
            }
        }
    }
}
