//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Map4D.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class My_texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal My_texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Map4D.Resources.My texts", typeof(My_texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truy cập ít hơn 60.000 lượt.
        /// </summary>
        public static string AccessRequests {
            get {
                return ResourceManager.GetString("AccessRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truy cập 1000 lượt tiếp theo.
        /// </summary>
        public static string AccessRequestsPerNext {
            get {
                return ResourceManager.GetString("AccessRequestsPerNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to và.
        /// </summary>
        public static string AndBookmark {
            get {
                return ResourceManager.GetString("AndBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Áp dụng cho bản Web và Mobile).
        /// </summary>
        public static string ApDungChoBangWebVaMobile {
            get {
                return ResourceManager.GetString("ApDungChoBangWebVaMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ trên nền tảng Mobile.
        /// </summary>
        public static string BanDoTrenNenTangMobile {
            get {
                return ResourceManager.GetString("BanDoTrenNenTangMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ trên nền tảng Web.
        /// </summary>
        public static string BanDoTrenNenTangWeb {
            get {
                return ResourceManager.GetString("BanDoTrenNenTangWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản quyền năm 2018 từ.
        /// </summary>
        public static string Bảnquyền {
            get {
                return ResourceManager.GetString("Bảnquyền", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gói cơ bản.
        /// </summary>
        public static string BasicPackage {
            get {
                return ResourceManager.GetString("BasicPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các dịch vụ bổ sung.
        /// </summary>
        public static string CacDichVuBoSung {
            get {
                return ResourceManager.GetString("CacDichVuBoSung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các dịch vụ tương ứng.
        /// </summary>
        public static string CacDichVuTuongTac {
            get {
                return ResourceManager.GetString("CacDichVuTuongTac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các tương tác trên bản đồ.
        /// </summary>
        public static string CacTuongTacTrenBanDo {
            get {
                return ResourceManager.GetString("CacTuongTacTrenBanDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn quý khách đã góp ý cho chúng tôi.
        /// </summary>
        public static string CảmƠn {
            get {
                return ResourceManager.GetString("CảmƠn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn bạn đã quan tâm, chúng tôi đang xây dựng nội dung và sẽ trở lại sớm..
        /// </summary>
        public static string Camondaquantam {
            get {
                return ResourceManager.GetString("Camondaquantam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn bạn đã liên hệ với chúng tôi!.
        /// </summary>
        public static string Camongopy {
            get {
                return ResourceManager.GetString("Camongopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thân.
        /// </summary>
        public static string Cheers {
            get {
                return ResourceManager.GetString("Cheers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ đường.
        /// </summary>
        public static string ChiDuong {
            get {
                return ResourceManager.GetString("ChiDuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ đường.
        /// </summary>
        public static string ChỉĐường {
            get {
                return ResourceManager.GetString("ChỉĐường", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ đường theo nhiều hướng và nhiều phương tiện.
        /// </summary>
        public static string ChiDuongTheoNhieuHuong {
            get {
                return ResourceManager.GetString("ChiDuongTheoNhieuHuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.35 $.
        /// </summary>
        public static string ChiPhiCongThem {
            get {
                return ResourceManager.GetString("ChiPhiCongThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 $.
        /// </summary>
        public static string ChiPhiDauTien {
            get {
                return ResourceManager.GetString("ChiPhiDauTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 $.
        /// </summary>
        public static string ChiPhiTheoGio {
            get {
                return ResourceManager.GetString("ChiPhiTheoGio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi cung cấp gói tùy chọn cho doanh nghiệp.
        /// </summary>
        public static string ChungToiCungCapGoiDichVu {
            get {
                return ResourceManager.GetString("ChungToiCungCapGoiDichVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển đổi tọa độ (mã hóa địa lý).
        /// </summary>
        public static string ChuyenToaDo {
            get {
                return ResourceManager.GetString("ChuyenToaDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấn vào nút bên dưới để hoàn thành quá trình đăng ký..
        /// </summary>
        public static string ClickTheButtonBelow {
            get {
                return ResourceManager.GetString("ClickTheButtonBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công cụ chỉnh sửa basemap.
        /// </summary>
        public static string CongCuChinhSua {
            get {
                return ResourceManager.GetString("CongCuChinhSua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty IOTLink.
        /// </summary>
        public static string CôngtyIOTLink {
            get {
                return ResourceManager.GetString("CôngtyIOTLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tin nhắn!.
        /// </summary>
        public static string ContactEnterMessage {
            get {
                return ResourceManager.GetString("ContactEnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên của bạn!.
        /// </summary>
        public static string ContactEnterName {
            get {
                return ResourceManager.GetString("ContactEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tiêu đề!.
        /// </summary>
        public static string ContactEnterSubject {
            get {
                return ResourceManager.GetString("ContactEnterSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý với Điều khoản dịch vụ và Chính sách quyền riêng tư của Map4D ..
        /// </summary>
        public static string DaCoTaiKhoan {
            get {
                return ResourceManager.GetString("DaCoTaiKhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có sẵn tài khoản đăng nhập.
        /// </summary>
        public static string ĐãCóTàiKhoản {
            get {
                return ResourceManager.GetString("ĐãCóTàiKhoản", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đa nền tảng.
        /// </summary>
        public static string ĐaNềnTảng {
            get {
                return ResourceManager.GetString("ĐaNềnTảng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu.
        /// </summary>
        public static string Đăngký {
            get {
                return ResourceManager.GetString("Đăngký", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá map 4D.
        /// </summary>
        public static string Đăngkýngaybâygiờ {
            get {
                return ResourceManager.GetString("Đăngkýngaybâygiờ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string ĐăngNhập {
            get {
                return ResourceManager.GetString("ĐăngNhập", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string DangNhapMenu {
            get {
                return ResourceManager.GetString("DangNhapMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang này đang xây dựng.
        /// </summary>
        public static string Dangxaydung {
            get {
                return ResourceManager.GetString("Dangxaydung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục địa điểm.
        /// </summary>
        public static string DanhMucDiaDiem {
            get {
                return ResourceManager.GetString("DanhMucDiaDiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến mọi nơi thật dễ dàng.
        /// </summary>
        public static string ĐếnMọiNơiThậtDễDàng {
            get {
                return ResourceManager.GetString("ĐếnMọiNơiThậtDễDàng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa điểm.
        /// </summary>
        public static string DiaDiem {
            get {
                return ResourceManager.GetString("DiaDiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa điểm xung quanh.
        /// </summary>
        public static string DiaDiemXungQuanh {
            get {
                return ResourceManager.GetString("DiaDiemXungQuanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định tuyến:.
        /// </summary>
        public static string DinhTuyen {
            get {
                return ResourceManager.GetString("DinhTuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cung cấp các ví dụ về các phiên bản phát triển điển hình cho SDK Android, mỗi trong số đó bao gồm các triển khai của Android.
        /// </summary>
        public static string Doc_AndroidContent {
            get {
                return ResourceManager.GetString("Doc_AndroidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android SDK.
        /// </summary>
        public static string Doc_AndroidTitle {
            get {
                return ResourceManager.GetString("Doc_AndroidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cung cấp các ví dụ về các tính năng API dịch vụ bản đồ phổ biến và tổng quan nhanh về các tính năng cốt lõi của API dịch vụ bản đồ bằng cách xem xét ví dụ.
        /// </summary>
        public static string Doc_APIContent {
            get {
                return ResourceManager.GetString("Doc_APIContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API dịch vụ map.
        /// </summary>
        public static string Doc_APITitle {
            get {
                return ResourceManager.GetString("Doc_APITitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá.
        /// </summary>
        public static string Doc_Explorer {
            get {
                return ResourceManager.GetString("Doc_Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cung cấp giải pháp map 2D, 3D &amp; 4D trên các nền tảng Mobile (Android &amp; iOS) và Web. Cung cấp các ví dụ mẫu (sample) và tài liệu cho lập trình viên có thể nhanh chóng phát triển ứng dụng dựa trên map4d SDK.
        /// </summary>
        public static string Doc_Introduction {
            get {
                return ResourceManager.GetString("Doc_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cung cấp các ví dụ về các phiên bản phát triển điển hình cho SDK iOS, mỗi phiên bản bao gồm iOS.
        /// </summary>
        public static string Doc_IOSContent {
            get {
                return ResourceManager.GetString("Doc_IOSContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iOS SDK.
        /// </summary>
        public static string Doc_IOSTitle {
            get {
                return ResourceManager.GetString("Doc_IOSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhập mới ngày 31 tháng 12 năm 2018.
        /// </summary>
        public static string Doc_UpdatedTime {
            get {
                return ResourceManager.GetString("Doc_UpdatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cung cấp các ví dụ về các phiên bản  phát triển điển hình cho SDK Web, mỗi phiên bản triển khai Web.
        /// </summary>
        public static string Doc_WebContent {
            get {
                return ResourceManager.GetString("Doc_WebContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web SDK.
        /// </summary>
        public static string Doc_WebTitle {
            get {
                return ResourceManager.GetString("Doc_WebTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài Liệu.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đối với.
        /// </summary>
        public static string DoiVoi {
            get {
                return ResourceManager.GetString("DoiVoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối với bản Beta, dịch vụ cung cấp miễn phí 100%.
        /// </summary>
        public static string DoiVoiBangBeta {
            get {
                return ResourceManager.GetString("DoiVoiBangBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có tài khoản?.
        /// </summary>
        public static string DoNotHaveAnAccount {
            get {
                return ResourceManager.GetString("DoNotHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu 2D, 3D.
        /// </summary>
        public static string DuLieu2D3D {
            get {
                return ResourceManager.GetString("DuLieu2D3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dựng không gian thực tế ảo VR360.
        /// </summary>
        public static string DungKhongGianThucTeAo {
            get {
                return ResourceManager.GetString("DungKhongGianThucTeAo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng..
        /// </summary>
        public static string EmailDinhDang {
            get {
                return ResourceManager.GetString("EmailDinhDang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email là bắt buộc..
        /// </summary>
        public static string EmailLàBắtBuộc {
            get {
                return ResourceManager.GetString("EmailLàBắtBuộc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã tồn tại!.
        /// </summary>
        public static string EmailTontai {
            get {
                return ResourceManager.GetString("EmailTontai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Anh.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập vào tên hiển thị.
        /// </summary>
        public static string EnterDisplayName {
            get {
                return ResourceManager.GetString("EnterDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập email..
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu..
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá các bản phát hành mới nhất trên.
        /// </summary>
        public static string ExploreTheLatest {
            get {
                return ResourceManager.GetString("ExploreTheLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Client/img/Flag_viet_nam.png.
        /// </summary>
        public static string FlagLanguage {
            get {
                return ResourceManager.GetString("FlagLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to để được trợ giúp bất cứ lúc nào..
        /// </summary>
        public static string ForHelpAnyTime {
            get {
                return ResourceManager.GetString("ForHelpAnyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miễn phí.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GhiNhớ {
            get {
                return ResourceManager.GetString("GhiNhớ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhớ mật khẩu.
        /// </summary>
        public static string GhiNhớMậtKhẩu {
            get {
                return ResourceManager.GetString("GhiNhớMậtKhẩu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Là bản đồ duy nhất ở Việt Nam hiển thị bản đồ 4D theo thời gian thực. Được xây dựng từ nhiều lớp dữ liệu, sẵn sàng kết nối và hướng tới 1 thành phố thông minh trực tuyến. Hướng đến việc tích hợp nhiều ứng dụng vào một nơi cho việc quản lý nhà nước, phục vụ sản xuất kinh doanh cho doanh nghiệp và người dân..
        /// </summary>
        public static string GiớiThiệu1 {
            get {
                return ResourceManager.GetString("GiớiThiệu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gói dịch vụ &amp; Bảng giá.
        /// </summary>
        public static string GoiDichVu {
            get {
                return ResourceManager.GetString("GoiDichVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gói hỗ trợ.
        /// </summary>
        public static string GoiHoTro {
            get {
                return ResourceManager.GetString("GoiHoTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi đi.
        /// </summary>
        public static string GửiNgayBâyGiờ {
            get {
                return ResourceManager.GetString("GửiNgayBâyGiờ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ ứng dụng của bạn trên nền tảng mobile (Android &amp; iOS) và web.Với các tính năng: tìm kiếm địa điểm, tìm đường đi, xem thời tiết, xem bản đồ ở chế độ 2D/3D, xem bản đồ theo thời gian và không gian(4D).
        /// </summary>
        public static string HỗTrợỨngDụng {
            get {
                return ResourceManager.GetString("HỗTrợỨngDụng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string Hovaten {
            get {
                return ResourceManager.GetString("Hovaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string HọvàTên {
            get {
                return ResourceManager.GetString("HọvàTên", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu nút &quot;Xác nhận địa chỉ email của bạn&quot; ở trên không xuất hiện, hãy sao chép và dán URL này vào trình duyệt của bạn:.
        /// </summary>
        public static string IfTheConfirm {
            get {
                return ResourceManager.GetString("IfTheConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá.
        /// </summary>
        public static string Khámphá {
            get {
                return ResourceManager.GetString("Khámphá", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá dịch vụ tiện ích xung quanh.
        /// </summary>
        public static string KhámPháDỊchVụ {
            get {
                return ResourceManager.GetString("KhámPháDỊchVụ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá ứng dụng.
        /// </summary>
        public static string KhámPháExplore {
            get {
                return ResourceManager.GetString("KhámPháExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá.
        /// </summary>
        public static string KhamPhaExplore1 {
            get {
                return ResourceManager.GetString("KhamPhaExplore1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không chỉ mang hình ảnh thực tế lên trên bản đồ 3D, ngoài ra còn cho phép tương tác và điều chỉnh các đối tượng 3D của bạn.
        /// </summary>
        public static string KhôngChỉ {
            get {
                return ResourceManager.GetString("KhôngChỉ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ với chúng tôi.
        /// </summary>
        public static string LiênHệ {
            get {
                return ResourceManager.GetString("LiênHệ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liên hệ với chúng tôi..
        /// </summary>
        public static string LienHeVoiChungToiTaiDay {
            get {
                return ResourceManager.GetString("LienHeVoiChungToiTaiDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập không hợp lệ..
        /// </summary>
        public static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map4D cam kết cung cấp các gói dịch vụ cao cấp phù hợp cho doanh nghiệp. Nếu bạn muốn được hỗ trợ nhiều hơn về các dịch vụ của Map4D hoặc muốn hợp tác phát triển, xin vui lòng.
        /// </summary>
        public static string Map4DCamKet {
            get {
                return ResourceManager.GetString("Map4DCamKet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map 4D! sản phẩm với các tính năng mới được nhiều đối tác tin dùng và phát triển.
        /// </summary>
        public static string Map4DDuocdonnhan {
            get {
                return ResourceManager.GetString("Map4DDuocdonnhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string MậtKhẩu {
            get {
                return ResourceManager.GetString("MậtKhẩu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mỗi địa điểm bạn tới đều có những dịch vụ cần thiết được hỗ trợ. Map 4D với kho dữ liệu địa điểm khổng lồ, đầy đủ các tiện ích, giúp bạn dễ dàng tìm kiếm và khám phá..
        /// </summary>
        public static string MỗiĐiaiemBanToi {
            get {
                return ResourceManager.GetString("MỗiĐiaiemBanToi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÊM THÔNG TIN.
        /// </summary>
        public static string MoreInformation {
            get {
                return ResourceManager.GetString("MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nền tảng Map4D.
        /// </summary>
        public static string NềntảngMap4D {
            get {
                return ResourceManager.GetString("NềntảngMap4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string Ngônngữ {
            get {
                return ResourceManager.GetString("Ngônngữ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng tự tải các đối tượng 3D lên bản đồ.
        /// </summary>
        public static string NguoiDungTuTai {
            get {
                return ResourceManager.GetString("NguoiDungTuTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map 4D thể hiện đầy đủ các công nghệ hiện đại từ không gian ảo tới hình ảnh thực tế được xây dựng trên nền tảng 3D..
        /// </summary>
        public static string NguyenThanhHuong {
            get {
                return ResourceManager.GetString("NguyenThanhHuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map 4D được đón nhận và tin cậy với hàng trăm người dùng trên toàn thế giới..
        /// </summary>
        public static string NguyenVanLinh {
            get {
                return ResourceManager.GetString("NguyenVanLinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xong.
        /// </summary>
        public static string notifyRegisterButtonPopup {
            get {
                return ResourceManager.GetString("notifyRegisterButtonPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng xác nhận email.
        /// </summary>
        public static string notifyRegisterConfirmMail {
            get {
                return ResourceManager.GetString("notifyRegisterConfirmMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thất bại.
        /// </summary>
        public static string notifyRegisterFail {
            get {
                return ResourceManager.GetString("notifyRegisterFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thành công.
        /// </summary>
        public static string notifyRegisterSuccess {
            get {
                return ResourceManager.GetString("notifyRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi đã gửi một email cho bạn.
        /// </summary>
        public static string PageFogot_daguimail {
            get {
                return ResourceManager.GetString("PageFogot_daguimail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập Map4D.
        /// </summary>
        public static string PageFogot_dangnhapMap4d {
            get {
                return ResourceManager.GetString("PageFogot_dangnhapMap4d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi hướng dẫn cài đặt lại.
        /// </summary>
        public static string PageFogot_guihuongdancailai {
            get {
                return ResourceManager.GetString("PageFogot_guihuongdancailai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khôi phục mật khẩu.
        /// </summary>
        public static string PageFogot_khoiphucmatkhau {
            get {
                return ResourceManager.GetString("PageFogot_khoiphucmatkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có tài khoản nào được liên kết với email.
        /// </summary>
        public static string PageFogot_khongcotaikhoan {
            get {
                return ResourceManager.GetString("PageFogot_khongcotaikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể khôi phục mật khẩu.
        /// </summary>
        public static string PageFogot_khongthekhoiphucmatkhau {
            get {
                return ResourceManager.GetString("PageFogot_khongthekhoiphucmatkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý.
        /// </summary>
        public static string PageFogot_ok {
            get {
                return ResourceManager.GetString("PageFogot_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu ?.
        /// </summary>
        public static string PageFogot_quenmatkhau {
            get {
                return ResourceManager.GetString("PageFogot_quenmatkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản chưa được xác nhận trước đó.
        /// </summary>
        public static string PageFogot_taikhoanchuaxacnhan {
            get {
                return ResourceManager.GetString("PageFogot_taikhoanchuaxacnhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng truy cập email để tiến hành thiết lập mật khẩu mới.
        /// </summary>
        public static string PageFogot_truycapmail {
            get {
                return ResourceManager.GetString("PageFogot_truycapmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng thử một email khác..
        /// </summary>
        public static string PageFogot_vuilongthumailkhac {
            get {
                return ResourceManager.GetString("PageFogot_vuilongthumailkhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng xác nhận tài khoản trước để thực hiện chức năng này.
        /// </summary>
        public static string PageFogot_vuilongxacnhantruoc {
            get {
                return ResourceManager.GetString("PageFogot_vuilongxacnhantruoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mỗi giờ.
        /// </summary>
        public static string PerHours {
            get {
                return ResourceManager.GetString("PerHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cộng thêm.
        /// </summary>
        public static string Plus {
            get {
                return ResourceManager.GetString("Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng giá.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên đăng nhập..
        /// </summary>
        public static string RegisterEnterUserName {
            get {
                return ResourceManager.GetString("RegisterEnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập đã tồn tại..
        /// </summary>
        public static string RegisterExistUserName {
            get {
                return ResourceManager.GetString("RegisterExistUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký Map4D.
        /// </summary>
        public static string RegisterMap4D {
            get {
                return ResourceManager.GetString("RegisterMap4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên người dùng hoặc email..
        /// </summary>
        public static string RequiredEmailLogin {
            get {
                return ResourceManager.GetString("RequiredEmailLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giải Pháp.
        /// </summary>
        public static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gói hỗ trợ.
        /// </summary>
        public static string SupportPackage {
            get {
                return ResourceManager.GetString("SupportPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đội Map4D.
        /// </summary>
        public static string TeamMap4D {
            get {
                return ResourceManager.GetString("TeamMap4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string TênĐăngNhập {
            get {
                return ResourceManager.GetString("TênĐăngNhập", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hiển thị.
        /// </summary>
        public static string TenHienThi {
            get {
                return ResourceManager.GetString("TenHienThi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to giá theo từng lượt truy cập.
        /// </summary>
        public static string ThePriceIsDependOnRequest {
            get {
                return ResourceManager.GetString("ThePriceIsDependOnRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liên hệ hỗ trợ.
        /// </summary>
        public static string TheSupportContactFrom {
            get {
                return ResourceManager.GetString("TheSupportContactFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời tiết, thời gian thực.
        /// </summary>
        public static string ThoiTietVaThoiGianThuc {
            get {
                return ResourceManager.GetString("ThoiTietVaThoiGianThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông cảm, chúng tôi đang xây dựng trang này.
        /// </summary>
        public static string ThôngCảm {
            get {
                return ResourceManager.GetString("ThôngCảm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn quý khách đã liên hệ với chúng tôi, chúng tôi sẽ phản hồi lại quý khách trong thời gian sớm nhất.
        /// </summary>
        public static string ThuCamOn {
            get {
                return ResourceManager.GetString("ThuCamOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiện ích địa điểm.
        /// </summary>
        public static string TiệnÍchĐịaChỉ {
            get {
                return ResourceManager.GetString("TiệnÍchĐịaChỉ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string Tiêuđề {
            get {
                return ResourceManager.GetString("Tiêuđề", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string TieuDeDangKy {
            get {
                return ResourceManager.GetString("TieuDeDangKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư cảm ơn.
        /// </summary>
        public static string TieuDeMail {
            get {
                return ResourceManager.GetString("TieuDeMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm:.
        /// </summary>
        public static string TimKiem {
            get {
                return ResourceManager.GetString("TimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính năng dẫn đường giúp bạn đến mọi nơi mà không cần phải biết chính xác địa điểm.Map 4D tự động tính toán tìm đường đi ngắn nhất giữa nhiều điểm trên bản đồ, hỗ trợ đầy đủ các loại phương tiện (đi bộ, xe đạp, xe máy, ô tô)..
        /// </summary>
        public static string TínhNăngDẫnĐường {
            get {
                return ResourceManager.GetString("TínhNăngDẫnĐường", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin nhắn.
        /// </summary>
        public static string TinNhắn {
            get {
                return ResourceManager.GetString("TinNhắn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tọa độ bản đồ:.
        /// </summary>
        public static string ToaDoBanDo {
            get {
                return ResourceManager.GetString("ToaDoBanDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập tối thiểu 6 và tối đa 32 kí tự..
        /// </summary>
        public static string ToiThieu {
            get {
                return ResourceManager.GetString("ToiThieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tối ưu hóa kết quả.
        /// </summary>
        public static string ToiUuHoaKetQua {
            get {
                return ResourceManager.GetString("ToiUuHoaKetQua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tác của công ty.
        /// </summary>
        public static string Trảinghiệmcùngmap4D {
            get {
                return ResourceManager.GetString("Trảinghiệmcùngmap4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string TrangChu {
            get {
                return ResourceManager.GetString("TrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính năng rất hữu ích và tiện dụng đối với tài xế chúng tôi.
        /// </summary>
        public static string TranVanDuy {
            get {
                return ResourceManager.GetString("TranVanDuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi đặc biệt ấn tượng với chức năng hiển thị bản đồ theo thời gian..
        /// </summary>
        public static string TranVanQuy {
            get {
                return ResourceManager.GetString("TranVanQuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D trực quan.
        /// </summary>
        public static string TrựcQuan3D {
            get {
                return ResourceManager.GetString("TrựcQuan3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ứng dụng.
        /// </summary>
        public static string Ứngdụng {
            get {
                return ResourceManager.GetString("Ứngdụng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy đăng ký.
        /// </summary>
        public static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc email.
        /// </summary>
        public static string UsernameOrEmail {
            get {
                return ResourceManager.GetString("UsernameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        public static string VietNam {
            get {
                return ResourceManager.GetString("VietNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem email này trực tuyến.
        /// </summary>
        public static string ViewThisEmailOnline {
            get {
                return ResourceManager.GetString("ViewThisEmailOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi hy vọng bạn sẽ thích Map4D!.
        /// </summary>
        public static string WeHopeYou {
            get {
                return ResourceManager.GetString("WeHopeYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        public static string XacNhanMatKhau {
            get {
                return ResourceManager.GetString("XacNhanMatKhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu xác nhận không đúng.
        /// </summary>
        public static string XacNhanMatKhauValidate {
            get {
                return ResourceManager.GetString("XacNhanMatKhauValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xây dựng đối tượng 3D.
        /// </summary>
        public static string XayDungDoiTuong3D {
            get {
                return ResourceManager.GetString("XayDungDoiTuong3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vâng, đó là email của tôi.
        /// </summary>
        public static string YesItIsMyEmail {
            get {
                return ResourceManager.GetString("YesItIsMyEmail", resourceCulture);
            }
        }
    }
}
