//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Map4D.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class My_texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal My_texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Map4D.Resources.My texts", typeof(My_texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng giá.
        /// </summary>
        public static string Bảnggiá {
            get {
                return ResourceManager.GetString("Bảnggiá", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản quyền năm 2018 từ.
        /// </summary>
        public static string Bảnquyền {
            get {
                return ResourceManager.GetString("Bảnquyền", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn quý khách đã góp ý cho chúng tôi.
        /// </summary>
        public static string CảmƠn {
            get {
                return ResourceManager.GetString("CảmƠn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn bạn đã gửi ý kiến cho chúng tôi!.
        /// </summary>
        public static string CảmƠnGópÝ {
            get {
                return ResourceManager.GetString("CảmƠnGópÝ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ đường.
        /// </summary>
        public static string ChỉĐường {
            get {
                return ResourceManager.GetString("ChỉĐường", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        public static string CôngTy {
            get {
                return ResourceManager.GetString("CôngTy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty IOTLink.
        /// </summary>
        public static string CôngtyIOTLink {
            get {
                return ResourceManager.GetString("CôngtyIOTLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Email!.
        /// </summary>
        public static string ContactEnterEmail {
            get {
                return ResourceManager.GetString("ContactEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tin nhắn!.
        /// </summary>
        public static string ContactEnterMessage {
            get {
                return ResourceManager.GetString("ContactEnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên của bạn!.
        /// </summary>
        public static string ContactEnterName {
            get {
                return ResourceManager.GetString("ContactEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập chủ đề!.
        /// </summary>
        public static string ContactEnterSubject {
            get {
                return ResourceManager.GetString("ContactEnterSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có tài khoản?.
        /// </summary>
        public static string ĐãCóTàiKhoản {
            get {
                return ResourceManager.GetString("ĐãCóTàiKhoản", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đa nền tảng.
        /// </summary>
        public static string ĐaNềnTảng {
            get {
                return ResourceManager.GetString("ĐaNềnTảng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Đăngký {
            get {
                return ResourceManager.GetString("Đăngký", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký ngay bây giờ để sử dụng Map4D.
        /// </summary>
        public static string Đăngkýngaybâygiờ {
            get {
                return ResourceManager.GetString("Đăngkýngaybâygiờ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string ĐăngNhập {
            get {
                return ResourceManager.GetString("ĐăngNhập", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến mọi nơi thật dễ dàng.
        /// </summary>
        public static string ĐếnMọiNơiThậtDễDàng {
            get {
                return ResourceManager.GetString("ĐếnMọiNơiThậtDễDàng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng!.
        /// </summary>
        public static string EmailDinhDang {
            get {
                return ResourceManager.GetString("EmailDinhDang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email là bắt buộc!.
        /// </summary>
        public static string EmailLàBắtBuộc {
            get {
                return ResourceManager.GetString("EmailLàBắtBuộc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã tồn tại!.
        /// </summary>
        public static string EmailTontai {
            get {
                return ResourceManager.GetString("EmailTontai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Anh.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Client/img/Flag_of_Vietnam.svg.png.
        /// </summary>
        public static string FlagLanguage {
            get {
                return ResourceManager.GetString("FlagLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GhiNhớ {
            get {
                return ResourceManager.GetString("GhiNhớ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhớ mật khẩu.
        /// </summary>
        public static string GhiNhớMậtKhẩu {
            get {
                return ResourceManager.GetString("GhiNhớMậtKhẩu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giải Pháp.
        /// </summary>
        public static string GiảiPháp {
            get {
                return ResourceManager.GetString("GiảiPháp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Là bản đồ duy nhất ở Việt Nam hiển thị bản đồ 4D theo thời gian thực. Được xây dựng từ nhiều lớp dữ liệu, sẵn sàng kết nối và hướng tới 1 thành phố thông minh trực tuyến. Hướng đến việc tích hợp nhiều ứng dụng vào một nơi cho việc quản lý nhà nước, phục vụ sản xuất kinh doanh cho doanh nghiệp và người dân..
        /// </summary>
        public static string GiớiThiệu1 {
            get {
                return ResourceManager.GetString("GiớiThiệu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi ngay bây giờ.
        /// </summary>
        public static string GửiNgayBâyGiờ {
            get {
                return ResourceManager.GetString("GửiNgayBâyGiờ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ ứng dụng của bạn trên nền tảng mobile (Android &amp; iOS) và web.Với các tính năng: tìm kiếm địa điểm, tìm đường đi, xem thời tiết, xem bản đồ ở chế độ 2D/3D, xem bản đồ theo thời gian và không gian(4D).
        /// </summary>
        public static string HỗTrợỨngDụng {
            get {
                return ResourceManager.GetString("HỗTrợỨngDụng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string Hovaten {
            get {
                return ResourceManager.GetString("Hovaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string HọvàTên {
            get {
                return ResourceManager.GetString("HọvàTên", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá.
        /// </summary>
        public static string Khámphá {
            get {
                return ResourceManager.GetString("Khámphá", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá dịch vụ tiện ích xung quanh.
        /// </summary>
        public static string KhámPháDỊchVụ {
            get {
                return ResourceManager.GetString("KhámPháDỊchVụ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không chỉ mang hình ảnh thực tế lên trên bản đồ 3D, ngoài ra còn cho phép tương tác và điều chỉnh các đối tượng 3D của bạn.
        /// </summary>
        public static string KhôngChỉ {
            get {
                return ResourceManager.GetString("KhôngChỉ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ với chúng tôi.
        /// </summary>
        public static string LiênHệ {
            get {
                return ResourceManager.GetString("LiênHệ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập không hợp lệ..
        /// </summary>
        public static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map 4D được đón nhận và tin cậy với hàng trăm người dùng trên toàn thế giới..
        /// </summary>
        public static string Map4DDuocdonnhan {
            get {
                return ResourceManager.GetString("Map4DDuocdonnhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string MậtKhẩu {
            get {
                return ResourceManager.GetString("MậtKhẩu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu là bắt buộc!.
        /// </summary>
        public static string MatKhauBatBuoc {
            get {
                return ResourceManager.GetString("MatKhauBatBuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mỗi địa điểm bạn tới đều có những dịch vụ cần thiết được hỗ trợ. Map 4D với kho dữ liệu địa điểm khổng lồ, đầy đủ các tiện ích, giúp bạn dễ dàng tìm kiếm và khám phá..
        /// </summary>
        public static string MỗiĐiaiemBanToi {
            get {
                return ResourceManager.GetString("MỗiĐiaiemBanToi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nền tảng Map4D.
        /// </summary>
        public static string NềntảngMap4D {
            get {
                return ResourceManager.GetString("NềntảngMap4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string Ngônngữ {
            get {
                return ResourceManager.GetString("Ngônngữ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xong.
        /// </summary>
        public static string notifyRegisterButtonPopup {
            get {
                return ResourceManager.GetString("notifyRegisterButtonPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng xác nhận email.
        /// </summary>
        public static string notifyRegisterConfirmMail {
            get {
                return ResourceManager.GetString("notifyRegisterConfirmMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thất bại.
        /// </summary>
        public static string notifyRegisterFail {
            get {
                return ResourceManager.GetString("notifyRegisterFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thành công.
        /// </summary>
        public static string notifyRegisterSuccess {
            get {
                return ResourceManager.GetString("notifyRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string SanPham {
            get {
                return ResourceManager.GetString("SanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản Phẩm.
        /// </summary>
        public static string SảnPhẩm {
            get {
                return ResourceManager.GetString("SảnPhẩm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài Liệu.
        /// </summary>
        public static string TàiLiệu {
            get {
                return ResourceManager.GetString("TàiLiệu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string TênĐăngNhập {
            get {
                return ResourceManager.GetString("TênĐăngNhập", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập đã tồn tại!.
        /// </summary>
        public static string Tênđăngnhậpđãtồntại {
            get {
                return ResourceManager.GetString("Tênđăngnhậpđãtồntại", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập là bắt buộc!.
        /// </summary>
        public static string TênĐăngNhậpLàBắtBuộc {
            get {
                return ResourceManager.GetString("TênĐăngNhậpLàBắtBuộc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiện ích địa chỉ.
        /// </summary>
        public static string TiệnÍchĐịaChỉ {
            get {
                return ResourceManager.GetString("TiệnÍchĐịaChỉ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string Tiêuđề {
            get {
                return ResourceManager.GetString("Tiêuđề", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính năng dẫn đường giúp bạn đến mọi nơi mà không cần phải biết chính xác địa điểm.Map 4D tự động tính toán tìm đường đi ngắn nhất giữa nhiều điểm trên bản đồ, hỗ trợ đầy đủ các loại phương tiện (đi bộ, xe đạp, xe máy, ô tô)..
        /// </summary>
        public static string TínhNăngDẫnĐường {
            get {
                return ResourceManager.GetString("TínhNăngDẫnĐường", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin nhắn.
        /// </summary>
        public static string TinNhắn {
            get {
                return ResourceManager.GetString("TinNhắn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập tối thiểu 6 và tối đa 32 kí tự!.
        /// </summary>
        public static string ToiThieu {
            get {
                return ResourceManager.GetString("ToiThieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trải nghiệm cùng map 4D.
        /// </summary>
        public static string Trảinghiệmcùngmap4D {
            get {
                return ResourceManager.GetString("Trảinghiệmcùngmap4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string TrangChu {
            get {
                return ResourceManager.GetString("TrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D trực quan.
        /// </summary>
        public static string TrựcQuan3D {
            get {
                return ResourceManager.GetString("TrựcQuan3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ứng dụng.
        /// </summary>
        public static string Ứngdụng {
            get {
                return ResourceManager.GetString("Ứngdụng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        public static string VietNam {
            get {
                return ResourceManager.GetString("VietNam", resourceCulture);
            }
        }
    }
}
